import { mock_newBoard_player_1, mock_newBoard_player_2 } from '../../mockData/newBoard.js';
import { mock_randomHits_player_1, mock_randomHits_player_2 } from '../../mockData/randomHits.js';

import automaticMode from './automaticMode.js';

const expectedResult = {
  gameLog: [
    { player: 'Player 1', target: 'A5', result: '🔥 Destroyer hit!' },
    { player: 'Player 2', target: 'C3', result: 'Miss' },
    { player: 'Player 1', target: 'D7', result: '🔥 Submarine hit!' },
    { player: 'Player 2', target: 'E6', result: 'Miss' },
    { player: 'Player 1', target: 'B2', result: 'Miss' },
    { player: 'Player 2', target: 'G2', result: '🔥 Patrol Boat hit!' },
    { player: 'Player 1', target: 'I6', result: 'Miss' },
    { player: 'Player 2', target: 'E1', result: 'Miss' },
    { player: 'Player 1', target: 'J7', result: '🔥 Battleship hit!' },
    { player: 'Player 2', target: 'C4', result: 'Miss' },
    { player: 'Player 1', target: 'F2', result: 'Miss' },
    { player: 'Player 2', target: 'D3', result: '🔥 Battleship hit!' },
    { player: 'Player 1', target: 'A2', result: 'Miss' },
    { player: 'Player 2', target: 'H5', result: 'Miss' },
    { player: 'Player 1', target: 'D6', result: '🔥 Submarine hit!' },
    { player: 'Player 2', target: 'D5', result: 'Miss' },
    { player: 'Player 1', target: 'G10', result: '🔥 Patrol Boat hit!' },
    { player: 'Player 2', target: 'E7', result: 'Miss' },
    { player: 'Player 1', target: 'A9', result: 'Miss' },
    { player: 'Player 2', target: 'J5', result: '🔥 Destroyer hit!' },
    { player: 'Player 1', target: 'D10', result: 'Miss' },
    { player: 'Player 2', target: 'B6', result: 'Miss' },
    { player: 'Player 1', target: 'J2', result: 'Miss' },
    { player: 'Player 2', target: 'G10', result: 'Miss' },
    { player: 'Player 1', target: 'C8', result: 'Miss' },
    { player: 'Player 2', target: 'I8', result: 'Miss' },
    { player: 'Player 1', target: 'A1', result: 'Miss' },
    { player: 'Player 2', target: 'D1', result: 'Miss' },
    { player: 'Player 1', target: 'C10', result: 'Miss' },
    { player: 'Player 2', target: 'I4', result: 'Miss' },
    { player: 'Player 1', target: 'E3', result: 'Miss' },
    { player: 'Player 2', target: 'G5', result: 'Miss' },
    { player: 'Player 1', target: 'J9', result: '🔥 Battleship hit!' },
    { player: 'Player 2', target: 'E5', result: 'Miss' },
    { player: 'Player 1', target: 'E10', result: 'Miss' },
    { player: 'Player 2', target: 'I6', result: 'Miss' },
    { player: 'Player 1', target: 'G9', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 2', target: 'I2', result: 'Miss' },
    { player: 'Player 1', target: 'F1', result: 'Miss' },
    { player: 'Player 2', target: 'C9', result: '🔥 Patrol Boat hit!' },
    { player: 'Player 1', target: 'B1', result: 'Miss' },
    { player: 'Player 2', target: 'F7', result: 'Miss' },
    { player: 'Player 1', target: 'A6', result: '🔥 Destroyer hit!' },
    { player: 'Player 2', target: 'G9', result: '🔥 Submarine hit!' },
    { player: 'Player 1', target: 'B10', result: 'Miss' },
    { player: 'Player 2', target: 'G3', result: '🔥 Battleship hit!' },
    { player: 'Player 1', target: 'H2', result: '🔥 Destroyer hit!' },
    { player: 'Player 2', target: 'J2', result: 'Miss' },
    { player: 'Player 1', target: 'I5', result: 'Miss' },
    { player: 'Player 2', target: 'E10', result: '🔥 Submarine hit!' },
    { player: 'Player 1', target: 'B6', result: 'Miss' },
    { player: 'Player 2', target: 'A1', result: 'Miss' },
    { player: 'Player 1', target: 'A3', result: 'Miss' },
    { player: 'Player 2', target: 'D10', result: '🔥 Submarine hit!' },
    { player: 'Player 1', target: 'F3', result: 'Miss' },
    { player: 'Player 2', target: 'F4', result: 'Miss' },
    { player: 'Player 1', target: 'E9', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 2', target: 'D8', result: 'Miss' },
    { player: 'Player 1', target: 'C5', result: '🔥 Submarine hit!' },
    { player: 'Player 2', target: 'A2', result: 'Miss' },
    { player: 'Player 1', target: 'J8', result: '🔥 Battleship hit!' },
    { player: 'Player 2', target: 'J3', result: '🔥 Destroyer hit!' },
    { player: 'Player 1', target: 'H8', result: 'Miss' },
    { player: 'Player 2', target: 'H6', result: 'Miss' },
    { player: 'Player 1', target: 'E6', result: 'Miss' },
    { player: 'Player 2', target: 'B1', result: 'Miss' },
    { player: 'Player 1', target: 'J5', result: 'Miss' },
    { player: 'Player 2', target: 'C6', result: 'Miss' },
    { player: 'Player 1', target: 'F6', result: 'Miss' },
    { player: 'Player 2', target: 'C8', result: '🔥 Patrol Boat hit!' },
    { player: 'Player 1', target: 'I7', result: 'Miss' },
    { player: 'Player 2', target: 'I10', result: 'Miss' },
    { player: 'Player 1', target: 'J4', result: 'Miss' },
    { player: 'Player 2', target: 'I5', result: 'Miss' },
    { player: 'Player 1', target: 'F8', result: 'Miss' },
    { player: 'Player 2', target: 'A9', result: 'Miss' },
    { player: 'Player 1', target: 'J3', result: 'Miss' },
    { player: 'Player 2', target: 'D4', result: 'Miss' },
    { player: 'Player 1', target: 'G1', result: 'Miss' },
    { player: 'Player 2', target: 'C10', result: 'Miss' },
    { player: 'Player 1', target: 'G3', result: 'Miss' },
    { player: 'Player 2', target: 'D9', result: 'Miss' },
    { player: 'Player 1', target: 'F10', result: '🔥 Patrol Boat hit!' },
    { player: 'Player 2', target: 'C1', result: 'Miss' },
    { player: 'Player 1', target: 'I3', result: 'Miss' },
    { player: 'Player 2', target: 'A5', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 1', target: 'A8', result: 'Miss' },
    { player: 'Player 2', target: 'B7', result: 'Miss' },
    { player: 'Player 1', target: 'I10', result: 'Miss' },
    { player: 'Player 2', target: 'J7', result: 'Miss' },
    { player: 'Player 1', target: 'E7', result: 'Miss' },
    { player: 'Player 2', target: 'H9', result: '🔥 Submarine hit!' },
    { player: 'Player 1', target: 'E2', result: 'Miss' },
    { player: 'Player 2', target: 'I7', result: 'Miss' },
    { player: 'Player 1', target: 'F9', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 2', target: 'J1', result: 'Miss' },
    { player: 'Player 1', target: 'I1', result: 'Miss' },
    { player: 'Player 2', target: 'D7', result: 'Miss' },
    { player: 'Player 1', target: 'G5', result: 'Miss' },
    { player: 'Player 2', target: 'G7', result: 'Miss' },
    { player: 'Player 1', target: 'E4', result: 'Miss' },
    { player: 'Player 2', target: 'G4', result: 'Miss' },
    { player: 'Player 1', target: 'J6', result: '🔥 Battleship hit!' },
    { player: 'Player 2', target: 'I1', result: 'Miss' },
    { player: 'Player 1', target: 'G2', result: '🔥 Destroyer hit!' },
    { player: 'Player 2', target: 'H7', result: 'Miss' },
    { player: 'Player 1', target: 'B4', result: '🔥 Patrol Boat hit!' },
    { player: 'Player 2', target: 'A3', result: 'Miss' },
    { player: 'Player 1', target: 'C3', result: '🔥 Submarine hit!' },
    { player: 'Player 2', target: 'H2', result: 'Miss' },
    { player: 'Player 1', target: 'H3', result: 'Miss' },
    { player: 'Player 2', target: 'B10', result: 'Miss' },
    { player: 'Player 1', target: 'G4', result: 'Miss' },
    { player: 'Player 2', target: 'H3', result: 'Miss' },
    { player: 'Player 1', target: 'H7', result: 'Miss' },
    { player: 'Player 2', target: 'B2', result: 'Miss' },
    { player: 'Player 1', target: 'B9', result: 'Miss' },
    { player: 'Player 2', target: 'B3', result: 'Miss' },
    { player: 'Player 1', target: 'C4', result: '🔥 Submarine hit!' },
    { player: 'Player 2', target: 'G8', result: 'Miss' },
    { player: 'Player 1', target: 'D3', result: 'Miss' },
    { player: 'Player 2', target: 'F8', result: 'Miss' },
    { player: 'Player 1', target: 'E1', result: 'Miss' },
    { player: 'Player 2', target: 'H8', result: 'Miss' },
    { player: 'Player 1', target: 'D4', result: 'Miss' },
    { player: 'Player 2', target: 'A7', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 1', target: 'C7', result: 'Miss' },
    { player: 'Player 2', target: 'E8', result: 'Miss' },
    { player: 'Player 1', target: 'I8', result: 'Miss' },
    { player: 'Player 2', target: 'C2', result: 'Miss' },
    { player: 'Player 1', target: 'I9', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 2', target: 'I3', result: 'Miss' },
    { player: 'Player 1', target: 'D9', result: 'Miss' },
    { player: 'Player 2', target: 'F6', result: 'Miss' },
    { player: 'Player 1', target: 'C9', result: 'Miss' },
    { player: 'Player 2', target: 'E3', result: '🔥 Battleship hit!' },
    { player: 'Player 1', target: 'H4', result: 'Miss' },
    { player: 'Player 2', target: 'B9', result: 'Miss' },
    { player: 'Player 1', target: 'E8', result: 'Miss' },
    { player: 'Player 2', target: 'C5', result: 'Miss' },
    { player: 'Player 1', target: 'G8', result: 'Miss' },
    { player: 'Player 2', target: 'A10', result: 'Miss' },
    { player: 'Player 1', target: 'F4', result: 'Miss' },
    { player: 'Player 2', target: 'G1', result: '🔥 Destroyer hit!' },
    { player: 'Player 1', target: 'C6', result: 'Miss' },
    { player: 'Player 2', target: 'F5', result: 'Miss' },
    { player: 'Player 1', target: 'H6', result: 'Miss' },
    { player: 'Player 2', target: 'E9', result: 'Miss' },
    { player: 'Player 1', target: 'B3', result: 'Miss' },
    { player: 'Player 2', target: 'J10', result: 'Miss' },
    { player: 'Player 1', target: 'F5', result: 'Miss' },
    { player: 'Player 2', target: 'D2', result: 'Miss' },
    { player: 'Player 1', target: 'G7', result: 'Miss' },
    { player: 'Player 2', target: 'D6', result: 'Miss' },
    { player: 'Player 1', target: 'D5', result: 'Miss' },
    { player: 'Player 2', target: 'B5', result: 'Miss' },
    { player: 'Player 1', target: 'J1', result: 'Miss' },
    { player: 'Player 2', target: 'F3', result: '🔥 Battleship hit!' },
    { player: 'Player 1', target: 'E5', result: 'Miss' },
    { player: 'Player 2', target: 'B8', result: 'Miss' },
    { player: 'Player 1', target: 'D1', result: 'Miss' },
    { player: 'Player 2', target: 'A8', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 1', target: 'I2', result: '🔥 Destroyer hit!' },
    { player: 'Player 2', target: 'F10', result: '🔥 Submarine hit!' },
    { player: 'Player 1', target: 'A4', result: '🔥 Destroyer hit!' },
    { player: 'Player 2', target: 'G6', result: 'Miss' },
    { player: 'Player 1', target: 'A7', result: 'Miss' },
    { player: 'Player 2', target: 'E2', result: 'Miss' },
    { player: 'Player 1', target: 'D8', result: '🔥 Submarine hit!' },
    { player: 'Player 2', target: 'J4', result: '🔥 Destroyer hit!' },
    { player: 'Player 1', target: 'I4', result: 'Miss' },
    { player: 'Player 2', target: 'F1', result: '🔥 Destroyer hit!' },
    { player: 'Player 1', target: 'G6', result: 'Miss' },
    { player: 'Player 2', target: 'J8', result: 'Miss' },
    { player: 'Player 1', target: 'A10', result: 'Miss' },
    { player: 'Player 2', target: 'E4', result: 'Miss' },
    { player: 'Player 1', target: 'B8', result: 'Miss' },
    { player: 'Player 2', target: 'A4', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 1', target: 'F7', result: 'Miss' },
    { player: 'Player 2', target: 'J6', result: 'Miss' },
    { player: 'Player 1', target: 'H9', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 2', target: 'C7', result: 'Miss' },
    { player: 'Player 1', target: 'C2', result: 'Miss' },
    { player: 'Player 2', target: 'A6', result: '🔥 Aircraft Carrier hit!' },
    { player: 'Player 1', target: 'B7', result: 'Miss' },
    { player: 'Player 2', target: 'J9', result: 'Miss' },
    { player: 'Player 1', target: 'C1', result: 'Miss' },
    { player: 'Player 2', target: 'F2', result: '🔥 Patrol Boat hit!' },
    { player: 'Player 1', target: 'H5', result: 'Miss' },
    { player: 'Player 2', target: 'H1', result: '🔥 Destroyer hit!' },
    { player: 'Player 1', target: 'B5', result: '🔥 Patrol Boat hit!' },
  ],
  winner: { player: 'Player 1', remainingShips: 1 },
};
describe('automaticMode', () => {
  it('Run automatic mode - expect player 1 to win with 1 ship part left', async () => {
    const result = await automaticMode({
      player1BoardData: mock_newBoard_player_1.data,
      player2BoardData: mock_newBoard_player_2.data,
      player1FiredData: mock_randomHits_player_1.data,
      player2FiredData: mock_randomHits_player_2.data,
    });
    expect(result).toEqual(expectedResult);
  });
  it('Run automatic mode - the game should return null if lacking data', async () => {
    const result = await automaticMode({
      player1BoardData: mock_newBoard_player_1.data,
      player2BoardData: mock_newBoard_player_2.data,
      player1FiredData: null,
      player2FiredData: mock_randomHits_player_2.data,
    });
    expect(result).toEqual({
      error: 'Missing game data!',
      gameLog: [],
      winner: null,
    });
  });
});
